### ISSUE TITLE
UX Fun Task

### ISSUE THREAD

**Issue by hridayesh-arya** [opencodeiiita/UrbanVentures#63]
# 🎮 UX Fun Task: Game On! 🎯  

**🚀 OPEN TO ALL. NO NEED TO CLAIM!**  
⏰ **LAST DATE: 22ND DEC, 7:00 PM SHARP!**  

---

Can there be an easier and more fun task than playing a game? Doubt it! 😏  

1️⃣ Head to this website on your **desktop** 🖥️🎮:  
[https://userinyerface.com/](https://userinyerface.com/)  

2️⃣ Complete the short game and take a screenshot 📸.  
3️⃣ In a doc file, share the screenshot, write about **how you felt** while playing, and reflect on the **importance of user interface and user experience**. Then, share the doc link in the **UX Fun Task** folder.  

---

**Plagiarism is strictly prohibited—share your own thoughts. After all, Opencode is all about learning! 🚀**  

**Good luck, team! 💪🔥 Let the fun begin!**

**Comment by kalim-Asim** [comment]
Claim

**Comment by HGRgamer** [comment]
claim
